package br.unb.frank.entity;

// Generated 29/01/2013 21:58:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Aluno generated by hbm2java
 */
@Entity
@Table(name = "aluno")
public class Aluno implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private int id;
    private String nome;
    private Set<Questionario> questionarios = new HashSet<Questionario>(0);
    private Set<Turma> turmas = new HashSet<Turma>(0);
    private Dimensao dimensao;
    private Usuario usuario;

    public Aluno() {
    }

    public Aluno(int id) {
	this.id = id;
    }

    public Aluno(int id, String nome, Set<Questionario> questionarios, Usuario usuario) {
	this.id = id;
	this.nome = nome;
	this.questionarios = questionarios;
	this.usuario= usuario;
    }

    @Id
    @SequenceGenerator(name = "aluno_id_seq", sequenceName = "aluno_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "aluno_id_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @Column(name = "nome")
    public String getNome() {
	return this.nome;
    }

    public void setNome(String nome) {
	this.nome = nome;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "aluno")
    public Set<Questionario> getQuestionarios() {
	return this.questionarios;
    }

    public void setQuestionarios(Set<Questionario> questionarios) {
	this.questionarios = questionarios;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "turma_aluno", joinColumns = @JoinColumn(name = "id_aluno"), inverseJoinColumns = @JoinColumn(name = "id_turma"))
    public Set<Turma> getTurmas() {
	return turmas;
    }

    public void setTurmas(Set<Turma> turmas) {
	this.turmas = turmas;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_dimensao")
    public Dimensao getDimensao() {
	return dimensao;
    }

    public void setDimensao(Dimensao dimensao) {
	this.dimensao = dimensao;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_usuario")
    public Usuario getUsuario() {
	return usuario;
    }

    public void setUsuario(Usuario usuario) {
	this.usuario = usuario;
    }

}
