package br.unb.frank.entity;

// Generated 29/01/2013 22:34:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente")
public class Docente implements java.io.Serializable {

    private int id;
    private String nome;
    private String login;
    private String password;
    private Set<Turma> turmas = new HashSet<Turma>(0);

    public Docente() {
    }

    public Docente(int id, String nome) {
	this.id = id;
	this.nome = nome;
    }

    public Docente(int id, String nome, String login, String password,
	    Set<Turma> turmas) {
	this.id = id;
	this.nome = nome;
	this.login = login;
	this.password = password;
	this.turmas = turmas;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @Column(name = "nome", nullable = false)
    @NotNull
    public String getNome() {
	return this.nome;
    }

    public void setNome(String nome) {
	this.nome = nome;
    }

    @Column(name = "login")
    public String getLogin() {
	return this.login;
    }

    public void setLogin(String login) {
	this.login = login;
    }

    @Column(name = "password")
    public String getPassword() {
	return this.password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
    public Set<Turma> getTurmas() {
	return this.turmas;
    }

    public void setTurmas(Set<Turma> turmas) {
	this.turmas = turmas;
    }

}
