package br.unb.frank.entity;

// Generated 29/01/2013 21:58:44 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Questionario generated by hbm2java
 */
@Entity
@Table(name = "questionario")
public class Questionario implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private int id;
    private Aluno aluno;
    private String nome;
    private List<Resposta> respostas = new ArrayList<Resposta>(0);

    public Questionario() {
    }

    public Questionario(int id) {
	this.id = id;
    }

    public Questionario(int id, Aluno aluno, String nome) {
	this.id = id;
	this.aluno = aluno;
	this.nome = nome;
    }

    @Id
    @SequenceGenerator(name = "questionario_id_seq", sequenceName = "questionario_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "questionario_id_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_aluno")
    public Aluno getAluno() {
	return this.aluno;
    }

    public void setAluno(Aluno aluno) {
	this.aluno = aluno;
    }

    @Column(name = "nome")
    public String getNome() {
	return this.nome;
    }

    public void setNome(String nome) {
	this.nome = nome;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "pergunta")
    public List<Resposta> getRespostas() {
	return this.respostas;
    }

    public void setRespostas(List<Resposta> respostas) {
	this.respostas = respostas;
    }

}
