package br.unb.frank.entity;

// Generated 29/01/2013 21:58:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Resposta generated by hbm2java
 */
@Entity
@Table(name = "resposta")
public class Resposta implements java.io.Serializable {

    private int id;
    private Pergunta pergunta;
    private int opcaoEscolhida;

    public Resposta() {
    }

    public Resposta(int id, int opcaoEscolhida) {
	this.id = id;
	this.opcaoEscolhida = opcaoEscolhida;
    }

    public Resposta(int id, Pergunta pergunta, int opcaoEscolhida) {
	this.id = id;
	this.pergunta = pergunta;
	this.opcaoEscolhida = opcaoEscolhida;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pergunta")
    public Pergunta getPergunta() {
	return this.pergunta;
    }

    public void setPergunta(Pergunta pergunta) {
	this.pergunta = pergunta;
    }

    @Column(name = "opcao_escolhida", nullable = false)
    public int getOpcaoEscolhida() {
	return this.opcaoEscolhida;
    }

    public void setOpcaoEscolhida(int opcaoEscolhida) {
	this.opcaoEscolhida = opcaoEscolhida;
    }

}
