package br.unb.frank.entity;

// Generated 29/01/2013 22:34:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * Turma generated by hbm2java
 */
@Entity
@Table(name = "turma")
public class Turma implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private int id;
    private Docente docente;
    private Date dataInicio;
    private Date dataFim;
    private Set<Aluno> alunos = new HashSet<Aluno>(0);

    public Turma() {
    }

    public Turma(int id, Date dataInicio, Date dataFim) {
	this.id = id;
	this.dataInicio = dataInicio;
	this.dataFim = dataFim;
    }

    public Turma(int id, Docente docente, Date dataInicio, Date dataFim,
	    Set<Aluno> alunos) {
	this.id = id;
	this.docente = docente;
	this.dataInicio = dataInicio;
	this.dataFim = dataFim;
	this.alunos = alunos;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_docente")
    public Docente getDocente() {
	return this.docente;
    }

    public void setDocente(Docente docente) {
	this.docente = docente;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_inicio", nullable = false, length = 13)
    @NotNull
    public Date getDataInicio() {
	return this.dataInicio;
    }

    public void setDataInicio(Date dataInicio) {
	this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "data_fim", nullable = false, length = 13)
    @NotNull
    public Date getDataFim() {
	return this.dataFim;
    }

    public void setDataFim(Date dataFim) {
	this.dataFim = dataFim;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "turma_aluno", joinColumns = @JoinColumn(name = "id_turma"), inverseJoinColumns = @JoinColumn(name = "id_aluno"))
    public Set<Aluno> getAlunos() {
	return this.alunos;
    }

    public void setAlunos(Set<Aluno> alunos) {
	this.alunos = alunos;
    }

}
