package br.unb.frank.entity;

// Generated 29/01/2013 21:58:44 by Hibernate Tools 3.4.0.CR1

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

/**
 * Aluno generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private int id;
    private String login;
    private String senha;
    private Integer perfil;

    private List<Docente> docentes;
    private List<Aluno> alunos;

    public enum PerfilEnum {

	ADMINISTRADOR(1, "Administrador"), //
	PROFESSOR(2, "Professor"), //
	ALUNO(3, "Aluno");

	private final Integer id;
	private final String prefix;

	private PerfilEnum(Integer id, String prefix) {
	    this.id = id;
	    this.prefix = prefix;
	}

	public Integer getId() {
	    return id;
	}

	@Override
	public String toString() {
	    return prefix;
	}

    }

    public Usuario() {
    }

    public Usuario(int id) {
	this.id = id;
    }

    public Usuario(int id, String login, String senha) {
	this.id = id;
	this.login = login;
	this.senha = senha;
    }

    @Id
    @SequenceGenerator(name = "usuario_id_seq", sequenceName = "usuario_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "usuario_id_seq")
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @Column(name = "login")
    public String getLogin() {
	return this.login;
    }

    public void setLogin(String login) {
	this.login = login;
    }

    @Column(name = "senha", length = 75)
    @Size(max = 15)
    public String getSenha() {
	return this.senha;
    }

    public void setSenha(String senha) {
	this.senha = senha;
    }

    @Column(name = "perfil")
    public Integer getPerfil() {
	return perfil;
    }

    public void setPerfil(Integer perfil) {
	this.perfil = perfil;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "usuario")
    public List<Docente> getDocentes() {
	return this.docentes;
    }

    public void setDocentes(List<Docente> docentes) {
	this.docentes = docentes;
    }

    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "usuario")
    public List<Aluno> getAlunos() {
	return alunos;
    }

    public void setAlunos(List<Aluno> alunos) {
	this.alunos = alunos;
    }

    @Transient
    public boolean isAdministrador() {
	return isPerfil(PerfilEnum.ADMINISTRADOR);
    }

    @Transient
    public boolean isAluno() {
	return isPerfil(PerfilEnum.ALUNO);
    }

    @Transient
    public boolean isProfessor() {
	return isPerfil(PerfilEnum.PROFESSOR);
    }

    @Transient
    private boolean isPerfil(PerfilEnum perfil) {
	return perfil.getId().equals(getPerfil());
    }

}
